apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coredrop.serviceAccountName" . }}
  labels:
    {{- include "coredrop.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
